config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  
  resources :products do
    resources :comments
  end
  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]
  
  post 'simple_pages/thank_you'
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/thank_you'
  get 'simple_pages/index'
	root "simple_pages#landing_page"
  post 'payments/create'

  mount ActionCable.server => '/cable'

	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	validates :name, presence: true
	has_many :orders
	has_many :comments, dependent: :destroy

	def highest_rating_comment
	  comments.rating_desc.first&.rating
	end

	def lowest_rating_comment
		comments.rating_asc.first&.rating
	end

	def average_rating
	  comments.average(:rating).to_f
	end

	def self.search(search_term)
  	Product.where("name LIKE ?", "%#{search_term}%")
	end

	# models/product_view.rb
	  
  def views
    $redis.get("product:#{id}")
  end
  
  def viewed!
    $redis.incr("product:#{id}")
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
    @product.viewed!
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/#{params[:q]}#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb

<div class="product-reviews">
    <% @comments.each do |comment| %>
      <%= render comment %>
    <% end %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true, class: 'general-form') do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :product_image_url, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :author %><br>
    <%= form.text_field :colour, id: :product_colour, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :price %><br>
    <%= form.text_field :price, id: :product_price, class: 'form-control' %>
  </div>

  <div class="actions">
      <%= submit_tag("Submit", class:"btn btn-default btn-product") %>
  </div>

  <%= link_to 'Show', @product %> |
  <%= link_to 'Back', products_path %>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
      <p>
        <%= f.label :body, "Comments" %><br>
        <%= f.text_area :body, class: 'form-control' %>
      </p>

      <p>
        <div class="rating"></div>
      </p>

      <p>
        <%= f.submit "Submit", class:"btn btn-default" %>
      </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<% cache product do %>
  <div class="col-sm-2 col-md-4 col-lg-4 product">
    <div class="product-name">
    	<h1><%= product.name %></h1>
    </div>
    <div>
      <%= link_to image_tag(product.image_url, class: "product-image image-responsive"), product %>
    </div>
    <p class="product-description"><%= product.description %></p>
    <p class="product-price"><%= "$#{'%.2f' %(product.price.to_i / 100)}" %></p>
    <p>Average Rating: <div id="#average-rating" class="rated" data-score="<%= @product.average_rating %>"></div> </p>
    <% if signed_in? && current_user.admin? %>
      <p class="destroy-product">
      	<%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %> |
      	<%= link_to 'Edit', edit_product_path(product) %>
      </p>
    <% end %>  
  </div><!-- /col -->
<% end %> <!-- end of cache -->
	

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form', product: @product %>

app/views/products/index.html.erb
<main class="wrapper">
  <header>
    <h2>Products</h2>
  </header>
  
  <div class="container-fluid">
    <div class="row">
      <% if @products.count > 0 %>
          <% cache(cache_key_for_products) do %>
              <%  @products.each do |product| %>
                  <%= render product %>
                <% end %>
            <% end %>
          <% else %>
            <br><b> No Products Found</b> <br>
          <% end %>
    </div> <!-- end of row -->
  </div> <!-- end of container -->
  
</main>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

app/views/products/show.html.erb
<div class ="container-fluid">
  <div class ="row" data-product-id="<%= @product.id %>">
    <div class="show-wrapper">
      <h2 class="product-show-name">
        <%= @product.name %>
      </h2>

      <div class="product-show-image-wrapper">
        <%= image_tag(@product.image_url, class: "img-zoom product-show-image image-responsive", data_zoom_image: "@product.image_url") %>
      </div>

      <h3>
        <strong>Price: </strong>
        <%= "$#{'%.2f' %(@product.price.to_i / 100)}" %>
      </h3>

      <div class="pay-button"><%= form_with(url: '/payments/create') do |form| %>
        <%= hidden_field_tag(:product_id, @product.id) %>
        <%= render partial: "shared/stripe_checkout_button" %>
      <% end %></div>

      <p class="product-show-description">
        <strong>Description: </strong>
        <%= @product.description %>
      </p>

      <p>Average Rating: <div id="#average-rating" class="rated" data-score="<%= @product.average_rating %>"></div> </p>

      <div class="product-review"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span> Highest rated review: <%= @product.highest_rating_comment %><br><br>
      <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span> Lowest rated review: <%= @product.lowest_rating_comment %></div>

      <h3>Comments</h3>

      <%= render 'comments' %>

      <%= will_paginate @comments %>
      <% if signed_in? && current_user.admin? %>
      <h6 class="viewed"> Views:
        <span class="badge">
          <%= @product.views %>
        </span>
      </h6>
      <p><%= link_to 'Edit', edit_product_path(@product) %> |
      <% end %>
      <%= link_to 'Back', products_path %></p>
    </div> <!-- end of show-wrapper -->
  </div> <!-- end of row -->
</div>  <!-- end of container -->