config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  
  resources :products do
    resources :comments
  end
  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]
  
  post 'simple_pages/thank_you'
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/thank_you'
  get 'simple_pages/index'
	root "simple_pages#landing_page"
  post 'payments/create'

  mount ActionCable.server => '/cable'

	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_application.html.erb
 	<nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-brand"><%= link_to "Red and Black Books", root_path %></div>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Find books by type <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Author</a></li>
                <li><a href="#">Title</a></li>
                <li><a href="#">Genre</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">New Releases</a></li>
              </ul>
            </li>
            <li><%= link_to "Products", products_path %></li>
            <li class="active"><%= link_to "About", simple_pages_about_path %><span class="sr-only">(current)</span></a></li>
            <li><%= link_to "Contact", simple_pages_contact_path %></li>
          </ul>
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Book Search">
            </div>
            <button type="submit" class="btn btn-default">Go</button>
          </form>
          
          <%= form_with(url: products_path, method: 'get', id: 'navbar-form navbar-left', class: 'form-control', html: {placeholder: "Book Search"}, local: true) do |form| %>
            <%= form.label :q, 'Search for:' %>
            <%= form.text_field :q, id: 'q', value: params[:q] %>
            <%= form.submit 'Search' %>
          <% end %>
            
          
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Log in <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

app/views/layouts/_footer.html.erb
<footer id="footer">
	<div class="footer-text">
  &copy; 2017 Red and Black Books
	</div>
</footer>

app/views/layouts/_navbar.html.erb
 	<nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div><%= link_to image_tag("logo.png", size: "195x80"), root_path %></div>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <!-- <li class="dropdown">
              
            </li> -->
            <li><%= link_to "Products", products_path %></li>
            <li><%= link_to "About", simple_pages_about_path %></li>
            <li><%= link_to "Contact", simple_pages_contact_path %></li>
            <li>
             <% if user_signed_in? %>
               <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
             <% else %>
               <%= link_to('Login', new_user_session_path) %>
             <% end %>
             <li>
              <% if user_signed_in? %>
                <%= link_to "Edit My Details", edit_user_registration_path %>
              <% else %>
              <% end %> 
              </li>
             
          </ul>

       <!--    <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Book Search">
            </div>
            <button type="submit" class="btn btn-default">Go</button>
          </form>
           -->
          <%= form_with(url: products_path, method: 'get', class:'navbar-form navbar-right', local: true) do |form| %>
            <div class="form-group">
            <%= form.label :q, 'Search for:' %>
            <%= text_field_tag(:q, "", type:"text", class:"form-control", placeholder:"Search") %>
            <%= submit_tag("Search", class:"btn btn-default") %>
          <% end %>
            
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Crimson Text" rel="stylesheet">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="header">
    </div>

    <% if notice %>
    <p class="notice alert-danger" role="alert"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger" role="alert"><%= alert %></p>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>